name: Deploy Frontend
on: [push]
#   push:
    # branches:
    #   - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: yarn install
      working-directory: ./frontend
    - name: Deploy to zeit now
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
      run: yarn now --token $ZEIT_TOKEN --prod --confirm
      working-directory: ./frontend