name: Deploy Backend
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
      working-directory: ./backend
    - name: Build
      run: |
        pipenv run python manage.py migrate --settings=config.settings.production
      working-directory: ./backend
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        ANNICT_ACCESS_TOKEN: ${{ secrets.ANNICT_ACCESS_TOKEN }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
    - name: Archive Production Artifact
      uses: actions/upload-artifact@v1
      with:
        name: backend
        path: ./backend
  deploy:
    name: Deploy to Heroku
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: backend
      - name: Deploy to Heroku
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: "animonit-test"
        run: git subtree push --prefix backend/ https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git master
